import gc

def get_form(data):
    gc.collect()
    yield """<html>"""
    yield """    <head>"""
    yield """        <link type="text/css" rel="stylesheet" href="css/irrigation.css">"""
    yield """        <title>Irrigation System Home Page</title>"""
    yield """    </head>"""
    yield """    <body>"""
    yield """    <h2>Network Configuration</h2>"""
    yield """        <div class="loader" id="spinnerLoader" style="display:none"></div>"""
    yield """        <form action="/config_wifi" method="post" id="wholeForm">"""
    yield """            <p>Select a Wifi Network</p>"""
    yield """            SSID: <select input type="text" name="ssid" id="inject_networks">"""
    yield """            </select><br><br>"""
    yield """            Password:  <input type="password" name="password" id="pwd">"""
    yield """            <input type="checkbox" onclick="showPwd()">Show Password"""
    yield """            <br><br>"""
    yield """            <input type="submit" value="OK" onclick="showDiv()">"""
    yield """            <input type="button" name="Cancel" value="Cancel" onClick="window.location='/';">"""
    yield """        </form>"""
    yield """    </body>"""
    yield """</html>"""
    yield """<script>"""
    yield """  var net_wrapper = document.getElementById("inject_networks");"""
    yield """  var nets = """ + str(data) + """;"""
    yield """  nets.forEach(el => {"""
    yield """   var option = document.createElement("option");"""
    yield """   option.value = el;"""
    yield """   option.text = el;"""
    yield """   net_wrapper.add(option);"""
    yield """  });"""
    yield """  function showPwd() {"""
    yield """      var x = document.getElementById("pwd");"""
    yield """      if (x.type === "password") {"""
    yield """        x.type = "text";"""
    yield """      } else {"""
    yield """        x.type = "password";"""
    yield """      }"""
    yield """ };"""
    yield """ function showDiv() {"""
    yield """      document.getElementById('wholeForm').style.display = "none";"""
    yield """      document.getElementById('spinnerLoader').style.display = "block";"""
    yield """ };"""
    yield """</script>"""

def confirmation(data):
    gc.collect()
    yield """<html>"""
    yield """    <p>Configuration was saved successfully.</p>"""
    yield """    <p>Your are now connected to <b>\"""" + str(data[0]) + """\"</b> Wifi with ip: <b>""" + str(data[1]) + """</b></p>"""
    yield """    <p>Your System is being restarted. You will be redirected to the home page in <span id="counter">20</span> second(s).</p>"""
    yield """</html>"""
    yield """<script type="text/javascript">"""
    yield """    function countdown() {"""
    yield """        var i = document.getElementById('counter');"""
    yield """        if (parseInt(i.innerHTML)<=0) {"""
    yield """            window.location.href = 'http://""" + str(data[1]) + """/';"""
    yield """        }"""
    yield """        if (parseInt(i.innerHTML)!=0) {"""
    yield """            i.innerHTML = parseInt(i.innerHTML)-1;"""
    yield """        }"""
    yield """    }"""
    yield """    setInterval(function(){ countdown(); },2000);"""
    yield """</script>"""

def enable_ap(data):
    gc.collect()
    yield """<html>"""
    yield """    <head><title>Irrigation System Home Page</title></head>"""
    yield """    <body>"""
    yield """       <p>Please connect to <b>'""" + str(data['ssid']) + """'</b> Wifi Network and"""
    yield """       <a href="http://""" + str(data['ip']) + """/config_wifi" title="Configuration Page">click here</a> to configure it</p>"""
    yield """    </body>"""
    yield """</html>"""